/**
 * Icon Registry
 *
 * Registry of all available Zion UI icons for use in the prototype builder.
 * Auto-generated from ux-zion-library/src/icons
 *
 * Total icons: 258
 *
 * To regenerate: node generate-icon-registry.js
 */

// All 258 icons from Zion UI library
export const ICON_REGISTRY = [
  // None option
  { value: 'none', label: 'None', category: 'None' },

  { value: 'ActivityBaseball', label: 'Activity Baseball', category: 'Activities' },
  { value: 'ActivityBasketball', label: 'Activity Basketball', category: 'Activities' },
  { value: 'ActivityFootball', label: 'Activity Football', category: 'Activities' },
  { value: 'ActivityLearn', label: 'Activity Learn', category: 'Activities' },
  { value: 'ActivityMusic', label: 'Activity Music', category: 'Activities' },
  { value: 'ActivityScience', label: 'Activity Science', category: 'Activities' },
  { value: 'ActivitySoccer', label: 'Activity Soccer', category: 'Activities' },
  { value: 'ActivityTennis', label: 'Activity Tennis', category: 'Activities' },
  { value: 'Add', label: 'Add', category: 'General' },
  { value: 'Arrow', label: 'Arrow', category: 'Navigation' },
  { value: 'ArrowCaret', label: 'Arrow Caret', category: 'Navigation' },
  { value: 'ArrowChange', label: 'Arrow Change', category: 'Navigation' },
  { value: 'ArrowRotate', label: 'Arrow Rotate', category: 'Navigation' },
  { value: 'ArrowSwap', label: 'Arrow Swap', category: 'Navigation' },
  { value: 'BackwardArrow', label: 'Backward Arrow', category: 'Navigation' },
  { value: 'BackwardArrowCaret', label: 'Backward Arrow Caret', category: 'Navigation' },
  { value: 'Calendar', label: 'Calendar', category: 'General' },
  { value: 'Check', label: 'Check', category: 'General' },
  { value: 'Close', label: 'Close', category: 'General' },
  { value: 'ContentAdd', label: 'Content Add', category: 'Content' },
  { value: 'ContentAttach', label: 'Content Attach', category: 'Content' },
  { value: 'ContentAttached', label: 'Content Attached', category: 'Content' },
  { value: 'ContentBookmark', label: 'Content Bookmark', category: 'Content' },
  { value: 'ContentCheck', label: 'Content Check', category: 'Content' },
  { value: 'ContentCompose', label: 'Content Compose', category: 'Content' },
  { value: 'ContentCopy', label: 'Content Copy', category: 'Content' },
  { value: 'ContentDelete', label: 'Content Delete', category: 'Content' },
  { value: 'ContentDetach', label: 'Content Detach', category: 'Content' },
  { value: 'ContentDownload', label: 'Content Download', category: 'Content' },
  { value: 'ContentEdit', label: 'Content Edit', category: 'Content' },
  { value: 'ContentFlag', label: 'Content Flag', category: 'Content' },
  { value: 'ContentHistory', label: 'Content History', category: 'Content' },
  { value: 'ContentLink', label: 'Content Link', category: 'Content' },
  { value: 'ContentLock', label: 'Content Lock', category: 'Content' },
  { value: 'ContentMoveDown', label: 'Content Move Down', category: 'Content' },
  { value: 'ContentMoveUp', label: 'Content Move Up', category: 'Content' },
  { value: 'ContentPrint', label: 'Content Print', category: 'Content' },
  { value: 'ContentRemove', label: 'Content Remove', category: 'Content' },
  { value: 'ContentReply', label: 'Content Reply', category: 'Content' },
  { value: 'ContentTag', label: 'Content Tag', category: 'Content' },
  { value: 'ContentUndo', label: 'Content Undo', category: 'Content' },
  { value: 'ContentUnlink', label: 'Content Unlink', category: 'Content' },
  { value: 'ContentUnlock', label: 'Content Unlock', category: 'Content' },
  { value: 'ContentUpload', label: 'Content Upload', category: 'Content' },
  { value: 'ControlBottomSheet', label: 'Control Bottom Sheet', category: 'Controls' },
  { value: 'ControlBrightnessLess', label: 'Control Brightness Less', category: 'Controls' },
  { value: 'ControlBrightnessMore', label: 'Control Brightness More', category: 'Controls' },
  { value: 'ControlContrastLess', label: 'Control Contrast Less', category: 'Controls' },
  { value: 'ControlContrastMore', label: 'Control Contrast More', category: 'Controls' },
  { value: 'ControlCrop', label: 'Control Crop', category: 'Controls' },
  { value: 'ControlDark', label: 'Control Dark', category: 'Controls' },
  { value: 'ControlDashboard', label: 'Control Dashboard', category: 'Controls' },
  { value: 'ControlDrag', label: 'Control Drag', category: 'Controls' },
  { value: 'ControlExpand', label: 'Control Expand', category: 'Controls' },
  { value: 'ControlExposure', label: 'Control Exposure', category: 'Controls' },
  { value: 'ControlFullscreen', label: 'Control Fullscreen', category: 'Controls' },
  { value: 'ControlFullscreenExit', label: 'Control Fullscreen Exit', category: 'Controls' },
  { value: 'ControlGrid', label: 'Control Grid', category: 'Controls' },
  { value: 'ControlHide', label: 'Control Hide', category: 'Controls' },
  { value: 'ControlHighlight', label: 'Control Highlight', category: 'Controls' },
  { value: 'ControlInvert', label: 'Control Invert', category: 'Controls' },
  { value: 'ControlList', label: 'Control List', category: 'Controls' },
  { value: 'ControlMove', label: 'Control Move', category: 'Controls' },
  { value: 'ControlReset', label: 'Control Reset', category: 'Controls' },
  { value: 'ControlSettingsAdjust', label: 'Control Settings Adjust', category: 'Controls' },
  { value: 'ControlSideSheet', label: 'Control Side Sheet', category: 'Controls' },
  { value: 'ControlSplit', label: 'Control Split', category: 'Controls' },
  { value: 'ControlTarget', label: 'Control Target', category: 'Controls' },
  { value: 'ControlTranslate', label: 'Control Translate', category: 'Controls' },
  { value: 'ControlView', label: 'Control View', category: 'Controls' },
  { value: 'ControlZoomIn', label: 'Control Zoom In', category: 'Controls' },
  { value: 'ControlZoomOut', label: 'Control Zoom Out', category: 'Controls' },
  { value: 'Copy', label: 'Copy', category: 'General' },
  { value: 'Delete', label: 'Delete', category: 'General' },
  { value: 'DiscoveryHeritage', label: 'Discovery Heritage', category: 'Discovery' },
  { value: 'DiscoveryNameMeaning', label: 'Discovery Name Meaning', category: 'Discovery' },
  { value: 'DiscoveryNamePopularity', label: 'Discovery Name Popularity', category: 'Discovery' },
  { value: 'DiscoveryPopulation', label: 'Discovery Population', category: 'Discovery' },
  { value: 'DiscoveryTradition', label: 'Discovery Tradition', category: 'Discovery' },
  { value: 'DiscoveryWheelchair', label: 'Discovery Wheelchair', category: 'Discovery' },
  { value: 'DocumentBasic', label: 'Document Basic', category: 'Documents' },
  { value: 'DocumentBlank', label: 'Document Blank', category: 'Documents' },
  { value: 'DocumentBook', label: 'Document Book', category: 'Documents' },
  { value: 'DocumentBookOpen', label: 'Document Book Open', category: 'Documents' },
  { value: 'DocumentBox', label: 'Document Box', category: 'Documents' },
  { value: 'DocumentCamera', label: 'Document Camera', category: 'Documents' },
  { value: 'DocumentCertificate', label: 'Document Certificate', category: 'Documents' },
  { value: 'DocumentCheck', label: 'Document Check', category: 'Documents' },
  { value: 'DocumentFolder', label: 'Document Folder', category: 'Documents' },
  { value: 'DocumentFolderCollection', label: 'Document Folder Collection', category: 'Documents' },
  { value: 'DocumentFolderLove', label: 'Document Folder Love', category: 'Documents' },
  { value: 'DocumentFolderOpen', label: 'Document Folder Open', category: 'Documents' },
  { value: 'DocumentFolderSmart', label: 'Document Folder Smart', category: 'Documents' },
  { value: 'DocumentImage', label: 'Document Image', category: 'Documents' },
  { value: 'DocumentImageBroken', label: 'Document Image Broken', category: 'Documents' },
  { value: 'DocumentInfo', label: 'Document Info', category: 'Documents' },
  { value: 'DocumentList', label: 'Document List', category: 'Documents' },
  { value: 'DocumentPdf', label: 'Document Pdf', category: 'Documents' },
  { value: 'DocumentPhoto', label: 'Document Photo', category: 'Documents' },
  { value: 'DocumentPrinted', label: 'Document Printed', category: 'Documents' },
  { value: 'DocumentRecordPerson', label: 'Document Record Person', category: 'Documents' },
  { value: 'DocumentRecordSearch', label: 'Document Record Search', category: 'Documents' },
  { value: 'DocumentSmart', label: 'Document Smart', category: 'Documents' },
  { value: 'DocumentStory', label: 'Document Story', category: 'Documents' },
  { value: 'DownArrow', label: 'Down Arrow', category: 'Navigation' },
  { value: 'DownArrowCaret', label: 'Down Arrow Caret', category: 'Navigation' },
  { value: 'Download', label: 'Download', category: 'General' },
  { value: 'Edit', label: 'Edit', category: 'General' },
  { value: 'EventBarBatMitzvah', label: 'Event Bar Bat Mitzvah', category: 'Events' },
  { value: 'EventBirth', label: 'Event Birth', category: 'Events' },
  { value: 'EventBurial', label: 'Event Burial', category: 'Events' },
  { value: 'EventCensus', label: 'Event Census', category: 'Events' },
  { value: 'EventChristening', label: 'Event Christening', category: 'Events' },
  { value: 'EventCourt', label: 'Event Court', category: 'Events' },
  { value: 'EventCremation', label: 'Event Cremation', category: 'Events' },
  { value: 'EventDeath', label: 'Event Death', category: 'Events' },
  { value: 'EventDivorce', label: 'Event Divorce', category: 'Events' },
  { value: 'EventHistorical', label: 'Event Historical', category: 'Events' },
  { value: 'EventImmigration', label: 'Event Immigration', category: 'Events' },
  { value: 'EventMarriage', label: 'Event Marriage', category: 'Events' },
  { value: 'EventMilitaryService', label: 'Event Military Service', category: 'Events' },
  { value: 'EventNaturalization', label: 'Event Naturalization', category: 'Events' },
  { value: 'EventNobility', label: 'Event Nobility', category: 'Events' },
  { value: 'EventOccupation', label: 'Event Occupation', category: 'Events' },
  { value: 'ForwardArrow', label: 'Forward Arrow', category: 'Navigation' },
  { value: 'ForwardArrowCaret', label: 'Forward Arrow Caret', category: 'Navigation' },
  { value: 'HelpAi', label: 'Help Ai', category: 'Help' },
  { value: 'HelpAnnouncement', label: 'Help Announcement', category: 'Help' },
  { value: 'HelpAskQuestion', label: 'Help Ask Question', category: 'Help' },
  { value: 'HelpCompass', label: 'Help Compass', category: 'Help' },
  { value: 'HelpPreserver', label: 'Help Preserver', category: 'Help' },
  { value: 'HelpTestDrive', label: 'Help Test Drive', category: 'Help' },
  { value: 'HelpTip', label: 'Help Tip', category: 'Help' },
  { value: 'HelpTouch', label: 'Help Touch', category: 'Help' },
  { value: 'Home', label: 'Home', category: 'General' },
  { value: 'Info', label: 'Info', category: 'General' },
  { value: 'Like', label: 'Like', category: 'General' },
  { value: 'LogoFamilysearch', label: 'Logo Familysearch', category: 'Logos' },
  { value: 'LogoRootstech', label: 'Logo Rootstech', category: 'Logos' },
  { value: 'MediaBackward', label: 'Media Backward', category: 'Media' },
  { value: 'MediaCamera', label: 'Media Camera', category: 'Media' },
  { value: 'MediaCameraRestricted', label: 'Media Camera Restricted', category: 'Media' },
  { value: 'MediaFilm', label: 'Media Film', category: 'Media' },
  { value: 'MediaForward', label: 'Media Forward', category: 'Media' },
  { value: 'MediaHeadphones', label: 'Media Headphones', category: 'Media' },
  { value: 'MediaMicrophone', label: 'Media Microphone', category: 'Media' },
  { value: 'MediaMicrophoneOff', label: 'Media Microphone Off', category: 'Media' },
  { value: 'MediaNext', label: 'Media Next', category: 'Media' },
  { value: 'MediaPause', label: 'Media Pause', category: 'Media' },
  { value: 'MediaPlay', label: 'Media Play', category: 'Media' },
  { value: 'MediaPrevious', label: 'Media Previous', category: 'Media' },
  { value: 'MediaSkipBackward15', label: 'Media Skip Backward15', category: 'Media' },
  { value: 'MediaSkipForward15', label: 'Media Skip Forward15', category: 'Media' },
  { value: 'MediaStop', label: 'Media Stop', category: 'Media' },
  { value: 'MediaVideoCamera', label: 'Media Video Camera', category: 'Media' },
  { value: 'MediaVolume', label: 'Media Volume', category: 'Media' },
  { value: 'MediaVolumeMute', label: 'Media Volume Mute', category: 'Media' },
  { value: 'Menu', label: 'Menu', category: 'Menus' },
  { value: 'MenuClose', label: 'Menu Close', category: 'Menus' },
  { value: 'MenuFilter', label: 'Menu Filter', category: 'Menus' },
  { value: 'MenuHome', label: 'Menu Home', category: 'Menus' },
  { value: 'MenuMore', label: 'Menu More', category: 'Menus' },
  { value: 'MenuNewWindow', label: 'Menu New Window', category: 'Menus' },
  { value: 'MenuSearch', label: 'Menu Search', category: 'Menus' },
  { value: 'MenuSettings', label: 'Menu Settings', category: 'Menus' },
  { value: 'More', label: 'More', category: 'General' },
  { value: 'Notice', label: 'Notice', category: 'Notices' },
  { value: 'NoticeBullet', label: 'Notice Bullet', category: 'Notices' },
  { value: 'NoticeDoNot', label: 'Notice Do Not', category: 'Notices' },
  { value: 'NoticeImportant', label: 'Notice Important', category: 'Notices' },
  { value: 'NoticeInfo', label: 'Notice Info', category: 'Notices' },
  { value: 'NoticeLoading', label: 'Notice Loading', category: 'Notices' },
  { value: 'NoticeLoadingMessage', label: 'Notice Loading Message', category: 'Notices' },
  { value: 'NoticeMute', label: 'Notice Mute', category: 'Notices' },
  { value: 'NoticeNewRelease', label: 'Notice New Release', category: 'Notices' },
  { value: 'NoticeProtected', label: 'Notice Protected', category: 'Notices' },
  { value: 'NoticeQuestion', label: 'Notice Question', category: 'Notices' },
  { value: 'NoticeSuggestion', label: 'Notice Suggestion', category: 'Notices' },
  { value: 'NoticeWarning', label: 'Notice Warning', category: 'Notices' },
  { value: 'Person', label: 'Person', category: 'People' },
  { value: 'PersonAdd', label: 'Person Add', category: 'People' },
  { value: 'PersonDuplicates', label: 'Person Duplicates', category: 'People' },
  { value: 'PersonFamily', label: 'Person Family', category: 'People' },
  { value: 'PersonFeatured', label: 'Person Featured', category: 'People' },
  { value: 'PersonGroup', label: 'Person Group', category: 'People' },
  { value: 'PersonRemove', label: 'Person Remove', category: 'People' },
  { value: 'PersonSearch', label: 'Person Search', category: 'People' },
  { value: 'PersonSpouse', label: 'Person Spouse', category: 'People' },
  { value: 'PlaceAmusement', label: 'Place Amusement', category: 'Places' },
  { value: 'PlaceCemetary', label: 'Place Cemetary', category: 'Places' },
  { value: 'PlaceChurch', label: 'Place Church', category: 'Places' },
  { value: 'PlaceCity', label: 'Place City', category: 'Places' },
  { value: 'PlaceCounty', label: 'Place County', category: 'Places' },
  { value: 'PlaceCourt', label: 'Place Court', category: 'Places' },
  { value: 'PlaceFarm', label: 'Place Farm', category: 'Places' },
  { value: 'PlaceHome', label: 'Place Home', category: 'Places' },
  { value: 'PlaceHospital', label: 'Place Hospital', category: 'Places' },
  { value: 'PlaceIsland', label: 'Place Island', category: 'Places' },
  { value: 'PlaceLowerDivision', label: 'Place Lower Division', category: 'Places' },
  { value: 'PlaceMilitary', label: 'Place Military', category: 'Places' },
  { value: 'PlaceOther', label: 'Place Other', category: 'Places' },
  { value: 'PlacePostOffice', label: 'Place Post Office', category: 'Places' },
  { value: 'PlaceProminentBuilding', label: 'Place Prominent Building', category: 'Places' },
  { value: 'PlaceRegion', label: 'Place Region', category: 'Places' },
  { value: 'PlaceStore', label: 'Place Store', category: 'Places' },
  { value: 'PlaceSuggestion', label: 'Place Suggestion', category: 'Places' },
  { value: 'PlaceTemple', label: 'Place Temple', category: 'Places' },
  { value: 'PlaceTribe', label: 'Place Tribe', category: 'Places' },
  { value: 'PlaceVillage', label: 'Place Village', category: 'Places' },
  { value: 'PlaceWorld', label: 'Place World', category: 'Places' },
  { value: 'Search', label: 'Search', category: 'General' },
  { value: 'Settings', label: 'Settings', category: 'General' },
  { value: 'Share', label: 'Share', category: 'General' },
  { value: 'SocialCall', label: 'Social Call', category: 'Social' },
  { value: 'SocialChat', label: 'Social Chat', category: 'Social' },
  { value: 'SocialComment', label: 'Social Comment', category: 'Social' },
  { value: 'SocialContributions', label: 'Social Contributions', category: 'Social' },
  { value: 'SocialEmail', label: 'Social Email', category: 'Social' },
  { value: 'SocialEmailOpen', label: 'Social Email Open', category: 'Social' },
  { value: 'SocialFaceContent', label: 'Social Face Content', category: 'Social' },
  { value: 'SocialFaceHappy', label: 'Social Face Happy', category: 'Social' },
  { value: 'SocialFaceLove', label: 'Social Face Love', category: 'Social' },
  { value: 'SocialFaceMad', label: 'Social Face Mad', category: 'Social' },
  { value: 'SocialFaceNeutral', label: 'Social Face Neutral', category: 'Social' },
  { value: 'SocialFaceSad', label: 'Social Face Sad', category: 'Social' },
  { value: 'SocialLike', label: 'Social Like', category: 'Social' },
  { value: 'SocialLove', label: 'Social Love', category: 'Social' },
  { value: 'SocialMessage', label: 'Social Message', category: 'Social' },
  { value: 'SocialSend', label: 'Social Send', category: 'Social' },
  { value: 'SocialShare', label: 'Social Share', category: 'Social' },
  { value: 'SocialStar', label: 'Social Star', category: 'Social' },
  { value: 'ThingBeaker', label: 'Thing Beaker', category: 'Things' },
  { value: 'ThingCalculator', label: 'Thing Calculator', category: 'Things' },
  { value: 'ThingCalendar', label: 'Thing Calendar', category: 'Things' },
  { value: 'ThingDevice', label: 'Thing Device', category: 'Things' },
  { value: 'ThingFlag', label: 'Thing Flag', category: 'Things' },
  { value: 'ThingFood', label: 'Thing Food', category: 'Things' },
  { value: 'ThingFuel', label: 'Thing Fuel', category: 'Things' },
  { value: 'ThingHandwriting', label: 'Thing Handwriting', category: 'Things' },
  { value: 'ThingMap', label: 'Thing Map', category: 'Things' },
  { value: 'ThingMapPin', label: 'Thing Map Pin', category: 'Things' },
  { value: 'ThingMoney', label: 'Thing Money', category: 'Things' },
  { value: 'ThingMovie', label: 'Thing Movie', category: 'Things' },
  { value: 'ThingOrdinanceCard', label: 'Thing Ordinance Card', category: 'Things' },
  { value: 'ThingPresentation', label: 'Thing Presentation', category: 'Things' },
  { value: 'ThingRecipe', label: 'Thing Recipe', category: 'Things' },
  { value: 'ThingStamp', label: 'Thing Stamp', category: 'Things' },
  { value: 'ThingStats', label: 'Thing Stats', category: 'Things' },
  { value: 'ThingTicket', label: 'Thing Ticket', category: 'Things' },
  { value: 'ThingTimer', label: 'Thing Timer', category: 'Things' },
  { value: 'ThingTrophy', label: 'Thing Trophy', category: 'Things' },
  { value: 'TreeDescendancy', label: 'Tree Descendancy', category: 'Trees' },
  { value: 'TreeFan', label: 'Tree Fan', category: 'Trees' },
  { value: 'TreePedigree', label: 'Tree Pedigree', category: 'Trees' },
  { value: 'TreeViewRelationship', label: 'Tree View Relationship', category: 'Trees' },
  { value: 'UpArrow', label: 'Up Arrow', category: 'Navigation' },
  { value: 'UpArrowCaret', label: 'Up Arrow Caret', category: 'Navigation' },
  { value: 'Upload', label: 'Upload', category: 'General' },
];

/**
 * Get all icon options organized by category
 */
export function getIconsByCategory() {
  const categories = {};

  ICON_REGISTRY.forEach(icon => {
    if (!categories[icon.category]) {
      categories[icon.category] = [];
    }
    categories[icon.category].push(icon);
  });

  return categories;
}

/**
 * Get all icons as flat array
 */
export function getAllIcons() {
  return ICON_REGISTRY;
}

/**
 * Find icon by value
 */
export function findIcon(value) {
  return ICON_REGISTRY.find(icon => icon.value === value);
}

/**
 * Get icon categories
 */
export function getIconCategories() {
  const categories = new Set();
  ICON_REGISTRY.forEach(icon => categories.add(icon.category));
  return Array.from(categories);
}
